// This file will be generated by the peppermint editor

#include <peppermint-preview/scripts/ScriptTypes.hpp>

peppermint::game::components::ScriptComponent* peppermint::scripts::createScriptComponent(unsigned int scriptType, vector<byte> bytes) {
	peppermint::game::components::ScriptComponent* out;

	switch (scriptType) {
	default:
		throw peppermint::exceptions::userScripts::UnknownScriptException();
	}

	out->deserialise(bytes);

	return out;
}